### PR TITLE
dark_theme-fix

### LINKED ISSUE #20: Dark theme Implementation for new DAPP

### PR DESCRIPTION
**Pull request by Aman035**
#20

### CODE REVIEW

**Comment by Aman035** [comment]
image
Issue with bottom padding or margin in dark theme

**Comment by zaryab2000** [comment]
@MdTeach Kindly start the review and Merge if its' all good

**Comment by zaryab2000** [comment]
ISSUE:

1. CTA symbol on channel creation page gets vanished in Dark Mode @koladebalogun . Will have to fix that

**Comment by zaryab2000** [comment]
@MdTeach Kindly review the Shareable Channel link part.

**Comment by Aman035** [comment]
image
Fix delegate modal for dark theme.
@koladebalogun @MdTeach

**Comment by Aman035** [comment]
image

Dark theme text not visible
@koladebalogun

**Comment by Aman035** [comment]
channel creation tab issues to be fixed on staging.

**Pull request merged**
